# Generated by Django 2.1 on 2019-04-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('discription', models.TextField(help_text='Enter a brief description of the course', max_length=2000)),
                ('syllabus', models.TextField(max_length=2000)),
                ('course_file', models.FileField(blank=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject_image', models.ImageField(upload_to='images/')),
                ('subject_body', models.TextField(max_length=1000)),
                ('subject_file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('teacher_image', models.ImageField(upload_to='images/')),
                ('mobile_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('body', models.TextField(max_length=1000)),
                ('subjects', models.ManyToManyField(help_text='Select a subject for this teacher', to='onlinesiksha.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(help_text='Select a subject for this course', to='onlinesiksha.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinesiksha.Teacher'),
        ),
    ]
