# Generated by Django 2.1 on 2019-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesiksha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='link',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
